name: Hello World
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 2"
